services:
  api:
    env_file:
      - ./.env
    image: glerystonmatos/quiron:${VERSAO}
    container_name: quiron-api
    restart: on-failure
    ports:
      - 5001:80
      - 5002:443
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ./arquivos:/app/arquivos
    networks:
      - quiron_net

networks:
  quiron_net:
    name: quiron_net