services:
  api:
    env_file:
      - ./.env
    image: glerystonmatos/quiron:${VERSAO}
    container_name: quiron-api
    restart: on-failure
    ports:
      - ${PORTA_HTTP_API}:80
      - ${PORTA_HTTPS_API}:443
    volumes:
      - ./arquivos:/app/arquivos
    networks:
      - quiron_net

networks:
  quiron_net:
    name: quiron_net